from distutils.core import setup

setup(
    name='wordTrend',
    version='1.0',
    packages=['venv.Lib.distutils', 'venv.Lib.encodings', 'venv.Lib.site-packages.pip',
              'venv.Lib.site-packages.pip.req', 'venv.Lib.site-packages.pip.vcs', 'venv.Lib.site-packages.pip.utils',
              'venv.Lib.site-packages.pip.compat', 'venv.Lib.site-packages.pip.models',
              'venv.Lib.site-packages.pip._vendor', 'venv.Lib.site-packages.pip._vendor.distlib',
              'venv.Lib.site-packages.pip._vendor.distlib._backport', 'venv.Lib.site-packages.pip._vendor.colorama',
              'venv.Lib.site-packages.pip._vendor.html5lib', 'venv.Lib.site-packages.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treebuilders', 'venv.Lib.site-packages.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip._vendor.progress', 'venv.Lib.site-packages.pip._vendor.requests',
              'venv.Lib.site-packages.pip._vendor.requests.packages',
              'venv.Lib.site-packages.pip._vendor.requests.packages.chardet',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3.util',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip._vendor.packaging', 'venv.Lib.site-packages.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip._vendor.webencodings', 'venv.Lib.site-packages.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip.commands', 'venv.Lib.site-packages.pip.operations',
              'venv.Lib.site-packages.html', 'venv.Lib.site-packages.http', 'venv.Lib.site-packages.past',
              'venv.Lib.site-packages.past.tests', 'venv.Lib.site-packages.past.types',
              'venv.Lib.site-packages.past.utils', 'venv.Lib.site-packages.past.builtins',
              'venv.Lib.site-packages.past.translation', 'venv.Lib.site-packages.queue', 'venv.Lib.site-packages.wheel',
              'venv.Lib.site-packages.wheel.test', 'venv.Lib.site-packages.wheel.test.simple.dist.simpledist',
              'venv.Lib.site-packages.wheel.test.complex-dist.complexdist', 'venv.Lib.site-packages.wheel.tool',
              'venv.Lib.site-packages.wheel.signatures', 'venv.Lib.site-packages.future',
              'venv.Lib.site-packages.future.moves', 'venv.Lib.site-packages.future.moves.dbm',
              'venv.Lib.site-packages.future.moves.html', 'venv.Lib.site-packages.future.moves.http',
              'venv.Lib.site-packages.future.moves.test', 'venv.Lib.site-packages.future.moves.urllib',
              'venv.Lib.site-packages.future.moves.xmlrpc', 'venv.Lib.site-packages.future.moves.tkinter',
              'venv.Lib.site-packages.future.tests', 'venv.Lib.site-packages.future.types',
              'venv.Lib.site-packages.future.utils', 'venv.Lib.site-packages.future.builtins',
              'venv.Lib.site-packages.future.backports', 'venv.Lib.site-packages.future.backports.html',
              'venv.Lib.site-packages.future.backports.http', 'venv.Lib.site-packages.future.backports.test',
              'venv.Lib.site-packages.future.backports.email', 'venv.Lib.site-packages.future.backports.email.mime',
              'venv.Lib.site-packages.future.backports.urllib', 'venv.Lib.site-packages.future.backports.xmlrpc',
              'venv.Lib.site-packages.future.standard_library', 'venv.Lib.site-packages.winreg',
              'venv.Lib.site-packages.xmlrpc', 'venv.Lib.site-packages._thread', 'venv.Lib.site-packages.copyreg',
              'venv.Lib.site-packages.reprlib', 'venv.Lib.site-packages.tkinter', 'venv.Lib.site-packages.twitter',
              'venv.Lib.site-packages.builtins', 'venv.Lib.site-packages.oauthlib',
              'venv.Lib.site-packages.oauthlib.oauth1', 'venv.Lib.site-packages.oauthlib.oauth1.rfc5849',
              'venv.Lib.site-packages.oauthlib.oauth1.rfc5849.endpoints', 'venv.Lib.site-packages.oauthlib.oauth2',
              'venv.Lib.site-packages.oauthlib.oauth2.rfc6749',
              'venv.Lib.site-packages.oauthlib.oauth2.rfc6749.clients',
              'venv.Lib.site-packages.oauthlib.oauth2.rfc6749.endpoints',
              'venv.Lib.site-packages.oauthlib.oauth2.rfc6749.grant_types', 'venv.Lib.site-packages.requests',
              'venv.Lib.site-packages.requests.packages', 'venv.Lib.site-packages.requests.packages.idna',
              'venv.Lib.site-packages.requests.packages.chardet', 'venv.Lib.site-packages.requests.packages.urllib3',
              'venv.Lib.site-packages.requests.packages.urllib3.util',
              'venv.Lib.site-packages.requests.packages.urllib3.contrib',
              'venv.Lib.site-packages.requests.packages.urllib3.packages',
              'venv.Lib.site-packages.requests.packages.urllib3.packages.backports',
              'venv.Lib.site-packages.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.setuptools', 'venv.Lib.site-packages.setuptools.extern',
              'venv.Lib.site-packages.setuptools.command', 'venv.Lib.site-packages._markupbase',
              'venv.Lib.site-packages.libfuturize', 'venv.Lib.site-packages.libfuturize.fixes',
              'venv.Lib.site-packages.socketserver', 'venv.Lib.site-packages._dummy_thread',
              'venv.Lib.site-packages.libpasteurize', 'venv.Lib.site-packages.libpasteurize.fixes',
              'venv.Lib.site-packages.pkg_resources', 'venv.Lib.site-packages.pkg_resources.extern',
              'venv.Lib.site-packages.pkg_resources._vendor', 'venv.Lib.site-packages.pkg_resources._vendor.packaging',
              'venv.Lib.site-packages.requests_oauthlib', 'venv.Lib.site-packages.requests_oauthlib.compliance_fixes',
              'spark', 'tweetAPI'],
    url='',
    license='',
    author='Kang',
    author_email='',
    description=''
)
