from distutils.core import setup

setup(
    name='wordTrend',
    version='',
    packages=['venv.lib.python2.7.distutils', 'venv.lib.python2.7.encodings', 'venv.lib.python2.7.site-packages.pip',
              'venv.lib.python2.7.site-packages.pip.req', 'venv.lib.python2.7.site-packages.pip.vcs',
              'venv.lib.python2.7.site-packages.pip.utils', 'venv.lib.python2.7.site-packages.pip.compat',
              'venv.lib.python2.7.site-packages.pip.models', 'venv.lib.python2.7.site-packages.pip._vendor',
              'venv.lib.python2.7.site-packages.pip._vendor.distlib',
              'venv.lib.python2.7.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python2.7.site-packages.pip._vendor.colorama',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python2.7.site-packages.pip._vendor.lockfile',
              'venv.lib.python2.7.site-packages.pip._vendor.progress',
              'venv.lib.python2.7.site-packages.pip._vendor.requests',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.chardet',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.util',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python2.7.site-packages.pip._vendor.packaging',
              'venv.lib.python2.7.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python2.7.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python2.7.site-packages.pip._vendor.webencodings',
              'venv.lib.python2.7.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python2.7.site-packages.pip.commands', 'venv.lib.python2.7.site-packages.pip.operations',
              'venv.lib.python2.7.site-packages.html', 'venv.lib.python2.7.site-packages.http',
              'venv.lib.python2.7.site-packages.past', 'venv.lib.python2.7.site-packages.past.tests',
              'venv.lib.python2.7.site-packages.past.types', 'venv.lib.python2.7.site-packages.past.utils',
              'venv.lib.python2.7.site-packages.past.builtins', 'venv.lib.python2.7.site-packages.past.translation',
              'venv.lib.python2.7.site-packages.queue', 'venv.lib.python2.7.site-packages.wheel',
              'venv.lib.python2.7.site-packages.wheel.test',
              'venv.lib.python2.7.site-packages.wheel.test.simple.dist.simpledist',
              'venv.lib.python2.7.site-packages.wheel.test.complex-dist.complexdist',
              'venv.lib.python2.7.site-packages.wheel.tool', 'venv.lib.python2.7.site-packages.wheel.signatures',
              'venv.lib.python2.7.site-packages.future', 'venv.lib.python2.7.site-packages.future.moves',
              'venv.lib.python2.7.site-packages.future.moves.dbm', 'venv.lib.python2.7.site-packages.future.moves.html',
              'venv.lib.python2.7.site-packages.future.moves.http',
              'venv.lib.python2.7.site-packages.future.moves.test',
              'venv.lib.python2.7.site-packages.future.moves.urllib',
              'venv.lib.python2.7.site-packages.future.moves.xmlrpc',
              'venv.lib.python2.7.site-packages.future.moves.tkinter', 'venv.lib.python2.7.site-packages.future.tests',
              'venv.lib.python2.7.site-packages.future.types', 'venv.lib.python2.7.site-packages.future.utils',
              'venv.lib.python2.7.site-packages.future.builtins', 'venv.lib.python2.7.site-packages.future.backports',
              'venv.lib.python2.7.site-packages.future.backports.html',
              'venv.lib.python2.7.site-packages.future.backports.http',
              'venv.lib.python2.7.site-packages.future.backports.test',
              'venv.lib.python2.7.site-packages.future.backports.email',
              'venv.lib.python2.7.site-packages.future.backports.email.mime',
              'venv.lib.python2.7.site-packages.future.backports.urllib',
              'venv.lib.python2.7.site-packages.future.backports.xmlrpc',
              'venv.lib.python2.7.site-packages.future.standard_library', 'venv.lib.python2.7.site-packages.winreg',
              'venv.lib.python2.7.site-packages.xmlrpc', 'venv.lib.python2.7.site-packages._thread',
              'venv.lib.python2.7.site-packages.copyreg', 'venv.lib.python2.7.site-packages.reprlib',
              'venv.lib.python2.7.site-packages.tkinter', 'venv.lib.python2.7.site-packages.twitter',
              'venv.lib.python2.7.site-packages.builtins', 'venv.lib.python2.7.site-packages.oauthlib',
              'venv.lib.python2.7.site-packages.oauthlib.oauth1',
              'venv.lib.python2.7.site-packages.oauthlib.oauth1.rfc5849',
              'venv.lib.python2.7.site-packages.oauthlib.oauth1.rfc5849.endpoints',
              'venv.lib.python2.7.site-packages.oauthlib.oauth2',
              'venv.lib.python2.7.site-packages.oauthlib.oauth2.rfc6749',
              'venv.lib.python2.7.site-packages.oauthlib.oauth2.rfc6749.clients',
              'venv.lib.python2.7.site-packages.oauthlib.oauth2.rfc6749.endpoints',
              'venv.lib.python2.7.site-packages.oauthlib.oauth2.rfc6749.grant_types',
              'venv.lib.python2.7.site-packages.requests', 'venv.lib.python2.7.site-packages.requests.packages',
              'venv.lib.python2.7.site-packages.requests.packages.idna',
              'venv.lib.python2.7.site-packages.requests.packages.chardet',
              'venv.lib.python2.7.site-packages.requests.packages.urllib3',
              'venv.lib.python2.7.site-packages.requests.packages.urllib3.util',
              'venv.lib.python2.7.site-packages.requests.packages.urllib3.contrib',
              'venv.lib.python2.7.site-packages.requests.packages.urllib3.packages',
              'venv.lib.python2.7.site-packages.requests.packages.urllib3.packages.backports',
              'venv.lib.python2.7.site-packages.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python2.7.site-packages.setuptools', 'venv.lib.python2.7.site-packages.setuptools.extern',
              'venv.lib.python2.7.site-packages.setuptools.command', 'venv.lib.python2.7.site-packages._markupbase',
              'venv.lib.python2.7.site-packages.libfuturize', 'venv.lib.python2.7.site-packages.libfuturize.fixes',
              'venv.lib.python2.7.site-packages.socketserver', 'venv.lib.python2.7.site-packages._dummy_thread',
              'venv.lib.python2.7.site-packages.libpasteurize', 'venv.lib.python2.7.site-packages.libpasteurize.fixes',
              'venv.lib.python2.7.site-packages.pkg_resources', 'venv.lib.python2.7.site-packages.pkg_resources.extern',
              'venv.lib.python2.7.site-packages.pkg_resources._vendor',
              'venv.lib.python2.7.site-packages.pkg_resources._vendor.packaging',
              'venv.lib.python2.7.site-packages.requests_oauthlib',
              'venv.lib.python2.7.site-packages.requests_oauthlib.compliance_fixes', 'spark', 'tweetAPI'],
    url='',
    license='',
    author='Kang',
    author_email='',
    description=''
)
